### ISSUE TITLE
Use URL as seed for randomly-generated cover backgrounds

### ISSUE THREAD

**Issue by joachimesque** [readeck/readeck#1]
# The problem:

Card covers (or I don't know how you call the big images) for two cards sharing the same URL don't have the same gradient colors. It is therefore highly illogical.

![image](https://user-images.githubusercontent.com/1781070/116894113-fc3a8280-ac31-11eb-83d7-db32012ee167.png)

# The solution:

Use the item URL as a seed to generate the gradient.

# Issue importance:

None whatsoever, but it could be nice don't you think?

**Comment by joachimesque** [comment]
(ಠ_ಠ)

![image](https://user-images.githubusercontent.com/1781070/116980174-36556400-acc6-11eb-8b0c-f2d75d9b8b9e.png)

**Comment by olivier-m** [comment]
I agree that it could use the URL (or a hash of it). I'll look into it.

I'll gladly take any good source of nice svg patterns if you happen to know where to find such a thing :)
